<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.l4y7yxp' shared service.

return $this->privates['.service_locator.l4y7yxp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\SystemWaryController::ajoutpartenaire' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SystemWaryController::ajoutsystem' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SystemWaryController:ajoutpartenaire' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SystemWaryController:ajoutsystem' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
], [
    'App\\Controller\\SystemWaryController::ajoutpartenaire' => '?',
    'App\\Controller\\SystemWaryController::ajoutsystem' => '?',
    'App\\Controller\\SystemWaryController:ajoutpartenaire' => '?',
    'App\\Controller\\SystemWaryController:ajoutsystem' => '?',
]);
