<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF4ulEvT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF4ulEvT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF4ulEvT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF4ulEvT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerF4ulEvT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'F4ulEvT',
    'container.build_id' => '594d70ca',
    'container.build_time' => 1565034781,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF4ulEvT');
