<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYClQV6f\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYClQV6f/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYClQV6f.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYClQV6f\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYClQV6f\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YClQV6f',
    'container.build_id' => '0be158a4',
    'container.build_time' => 1565100250,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYClQV6f');
