<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHePyHsQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHePyHsQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHePyHsQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHePyHsQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHePyHsQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HePyHsQ',
    'container.build_id' => '1ade3131',
    'container.build_time' => 1565018318,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHePyHsQ');
